import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  EnvironmentDiffReportSchema,
  EnvironmentValidationReportSchema,
  type EnvironmentDiffReport,
  type EnvironmentProfile,
  type EnvironmentValidationReport,
  type Workspace,
} from "@fdt/schemas";
import { allStartedResources, scanResources } from "@fdt/scanner";
import { buildWorkspaceDependencyGraph } from "./build-dependency-graph.js";
import {
  loadEnvironmentRegistry,
  prioritizeCoreEnsureOrder,
  resolveEnvironmentProfile,
} from "./environment-store.js";
import {
  FDT_ENVIRONMENT_DIFF_REPORT,
  FDT_ENVIRONMENT_VALIDATION_REPORT,
  FDT_TXADMIN_EXPORT_DIR,
} from "./workspace.js";

function generatedHeader(workspaceName: string): string {
  return [
    "# Generated by FiveM DevOps Toolkit",
    "# Do not edit this file directly unless you plan to stop regenerating it.",
    `# Source workspace: ${workspaceName}`,
    "",
  ].join("\n");
}

function resourceNameFromNodeId(nodeId: string): string | null {
  if (!nodeId.startsWith("resource:")) {
    return null;
  }
  return nodeId.slice("resource:".length);
}

export async function buildResourceEnsureOrder(
  workspaceRoot: string,
  workspace: Workspace,
  profile: EnvironmentProfile,
): Promise<string[]> {
  if (profile.ensureOrderOverride && profile.ensureOrderOverride.length > 0) {
    return prioritizeCoreEnsureOrder(profile.ensureOrderOverride);
  }

  const scanResult = await scanResources({ workspaceRoot, workspace });
  const started = allStartedResources(scanResult.serverCfg);
  const scannedNames = scanResult.resources.map((resource) => resource.name);
  const candidateSet = new Set<string>([...scannedNames, ...started]);

  if (candidateSet.size === 0) {
    return [];
  }

  const graph = await buildWorkspaceDependencyGraph(workspaceRoot, workspace);
  const dependencyEdges = graph.edges.filter(
    (edge) => edge.type === "depends_on" || edge.type === "runtime_depends_on",
  );

  const adjacency = new Map<string, Set<string>>();
  const inDegree = new Map<string, number>();

  for (const name of candidateSet) {
    adjacency.set(name, new Set());
    inDegree.set(name, 0);
  }

  for (const edge of dependencyEdges) {
    const source = resourceNameFromNodeId(edge.source);
    const target = resourceNameFromNodeId(edge.target);
    if (!source || !target || !candidateSet.has(source) || !candidateSet.has(target) || source === target) {
      continue;
    }

    if (!adjacency.get(target)!.has(source)) {
      adjacency.get(target)!.add(source);
      inDegree.set(source, (inDegree.get(source) ?? 0) + 1);
    }
  }

  const queue = [...candidateSet]
    .filter((name) => (inDegree.get(name) ?? 0) === 0)
    .sort((a, b) => a.localeCompare(b));
  const ordered: string[] = [];

  while (queue.length > 0) {
    const current = queue.shift()!;
    ordered.push(current);

    for (const dependent of [...(adjacency.get(current) ?? [])].sort((a, b) => a.localeCompare(b))) {
      const nextDegree = (inDegree.get(dependent) ?? 0) - 1;
      inDegree.set(dependent, nextDegree);
      if (nextDegree === 0) {
        queue.push(dependent);
        queue.sort((a, b) => a.localeCompare(b));
      }
    }
  }

  for (const name of [...candidateSet].sort((a, b) => a.localeCompare(b))) {
    if (!ordered.includes(name)) {
      ordered.push(name);
    }
  }

  if (started.length > 0) {
    const startedOrdered = started.filter((name) => ordered.includes(name));
    const remainder = ordered.filter((name) => !startedOrdered.includes(name));
    return prioritizeCoreEnsureOrder([...startedOrdered, ...remainder]);
  }

  return prioritizeCoreEnsureOrder(ordered);
}

export function renderServerCfgContent(input: {
  workspaceName: string;
  profile: EnvironmentProfile;
  ensureOrder: string[];
}): string {
  const { workspaceName, profile, ensureOrder } = input;
  const lines: string[] = [generatedHeader(workspaceName)];

  lines.push(`endpoint_add_tcp "${profile.endpoint}"`);
  lines.push(`endpoint_add_udp "${profile.endpoint}"`);
  lines.push(`sv_maxclients ${profile.maxClients}`);
  lines.push(`set onesync ${profile.onesync}`);
  lines.push(`sv_licenseKey ${profile.secrets.find((secret) => secret.key === "svLicense")?.placeholder ?? "{{svLicense}}"}`);
  lines.push("");

  for (const convar of profile.convars) {
    if (convar.comment) {
      lines.push(`# ${convar.comment}`);
    }
    lines.push(`set ${convar.key} "${convar.value}"`);
  }

  if (profile.database?.connectionString) {
    lines.push("");
    lines.push(`set mysql_connection_string "${profile.database.connectionString}"`);
  }

  lines.push("");
  lines.push("# Resource ensure order");
  for (const resource of ensureOrder) {
    lines.push(`ensure ${resource}`);
  }

  if (profile.extraServerCfgLines.length > 0) {
    lines.push("");
    lines.push("# Extra configuration");
    lines.push(...profile.extraServerCfgLines);
  }

  lines.push("");
  return lines.join("\n");
}

function yamlEscape(value: string): string {
  if (/[:#{}[\],&*?|>!%@`]/.test(value) || value.includes("\n")) {
    return JSON.stringify(value);
  }
  return value;
}

function yamlMultiline(value: string, indent = 4): string {
  const pad = " ".repeat(indent);
  return value
    .split("\n")
    .map((line) => `${pad}${line}`)
    .join("\n");
}

export function renderTxAdminRecipeContent(input: {
  workspaceName: string;
  profile: EnvironmentProfile;
  serverCfgContent: string;
}): string {
  const { workspaceName, profile, serverCfgContent } = input;
  const meta = profile.recipeMeta ?? {
    name: `${workspaceName}-${profile.kind}`,
    version: "1.0.0",
    author: "FiveM DevOps Toolkit",
    description: `${workspaceName} ${profile.kind} deployment recipe`,
  };

  const lines: string[] = [
    generatedHeader(workspaceName).replace(/^# /gm, "# "),
    `name: ${yamlEscape(meta.name)}`,
    `version: ${yamlEscape(meta.version)}`,
    `author: ${yamlEscape(meta.author)}`,
  ];

  if (meta.description) {
    lines.push("description: |");
    lines.push(yamlMultiline(meta.description, 2));
  }

  lines.push("");
  lines.push("variables:");
  lines.push(`  serverName: ${yamlEscape(profile.serverName)}`);
  lines.push(`  svLicense: ${yamlEscape(profile.secrets.find((secret) => secret.key === "svLicense")?.placeholder ?? "{{svLicense}}")}`);
  lines.push(`  maxClients: ${profile.maxClients}`);
  lines.push(`  onesync: ${yamlEscape(profile.onesync)}`);
  lines.push(`  endpoint: ${yamlEscape(profile.endpoint)}`);

  if (profile.database) {
    lines.push(`  dbHost: ${yamlEscape(profile.database.host)}`);
    lines.push(`  dbPort: ${profile.database.port}`);
    lines.push(`  dbUsername: ${yamlEscape(profile.database.username)}`);
    lines.push(`  dbPassword: ${yamlEscape(profile.database.password)}`);
    if (profile.database.database) {
      lines.push(`  dbName: ${yamlEscape(profile.database.database)}`);
    }
    lines.push(`  dbConnectionString: ${yamlEscape(profile.database.connectionString ?? "{{dbConnectionString}}")}`);
  }

  for (const secret of profile.secrets) {
    if (secret.key === "svLicense") {
      continue;
    }
    lines.push(`  ${secret.key}: ${yamlEscape(secret.placeholder)}`);
  }

  lines.push("");
  lines.push("tasks:");
  lines.push("  - action: ensure_dir");
  lines.push("    path: ./resources");
  lines.push("");
  lines.push("  - action: download_github");
  lines.push("    src: citizenfx/cfx-server-data");
  lines.push("    subpath: resources");
  lines.push("    dest: ./resources");
  lines.push("");
  lines.push("  - action: write_file");
  lines.push("    file: ./server.cfg");
  lines.push("    data: |");
  lines.push(yamlMultiline(serverCfgContent, 6));

  if (profile.database && (profile.kind === "staging" || profile.kind === "production")) {
    lines.push("");
    lines.push("  - action: connect_database");
    lines.push("");
    lines.push("  - action: replace_string");
    lines.push("    mode: all_vars");
    lines.push("    file: ./server.cfg");
  }

  lines.push("");
  return lines.join("\n");
}

export async function generateServerCfg(
  workspaceRoot: string,
  workspace: Workspace,
  profile: EnvironmentProfile,
): Promise<{ content: string; ensureOrder: string[]; outputPath: string }> {
  const ensureOrder = await buildResourceEnsureOrder(workspaceRoot, workspace, profile);
  const content = renderServerCfgContent({
    workspaceName: workspace.name,
    profile,
    ensureOrder,
  });

  const outputPath = path.join(
    workspaceRoot,
    FDT_TXADMIN_EXPORT_DIR,
    profile.id,
    "server.cfg",
  );
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content, "utf8");

  return { content, ensureOrder, outputPath };
}

export async function generateTxAdminRecipe(
  workspaceRoot: string,
  workspace: Workspace,
  profile: EnvironmentProfile,
): Promise<{ content: string; serverCfgPath: string; outputPath: string }> {
  const { content: serverCfgContent, outputPath: serverCfgPath } = await generateServerCfg(
    workspaceRoot,
    workspace,
    profile,
  );

  const content = renderTxAdminRecipeContent({
    workspaceName: workspace.name,
    profile,
    serverCfgContent,
  });

  const outputPath = path.join(
    workspaceRoot,
    FDT_TXADMIN_EXPORT_DIR,
    profile.id,
    "recipe.yaml",
  );
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content, "utf8");

  return { content, serverCfgPath, outputPath };
}

export function validateEnvironmentProfile(
  workspaceName: string,
  profile: EnvironmentProfile,
): EnvironmentValidationReport {
  const findings: EnvironmentValidationReport["findings"] = [];
  const secretPlaceholders = new Set(
    profile.secrets.flatMap((secret) => [secret.placeholder, `{{${secret.key}}}`]),
  );

  for (const secret of profile.secrets) {
    if (profile.kind === "production" && secret.requiredInProduction && secret.placeholder.trim().length === 0) {
      findings.push({
        severity: "error",
        code: "empty_secret_placeholder",
        message: `Production secret ${secret.key} has an empty placeholder`,
        field: secret.key,
      });
    }
  }

  const requiredKeys = ["svLicense"];
  for (const key of requiredKeys) {
    if (profile.kind === "production" && !profile.secrets.some((secret) => secret.key === key)) {
      findings.push({
        severity: "error",
        code: "missing_required_secret",
        message: `Production profile is missing required secret ${key}`,
        field: key,
      });
    }
  }

  for (const convar of profile.convars) {
    if (profile.kind !== "production") {
      continue;
    }

    const placeholders = convar.value.match(/\{\{[a-zA-Z0-9_]+\}\}/g) ?? [];
    for (const placeholder of placeholders) {
      if (!secretPlaceholders.has(placeholder)) {
        findings.push({
          severity: "error",
          code: "unresolved_placeholder",
          message: `Production convar ${convar.key} references unresolved placeholder ${placeholder}`,
          field: convar.key,
        });
      }
    }
  }

  if (profile.kind === "production" && profile.endpoint.startsWith("127.0.0.1")) {
    findings.push({
      severity: "warning",
      code: "local_endpoint_in_production",
      message: "Production profile uses a localhost endpoint",
      field: "endpoint",
    });
  }

  if (profile.database && profile.kind === "production") {
    for (const field of ["host", "username", "database", "connectionString"] as const) {
      const value = profile.database[field];
      if (typeof value === "string" && value.length === 0) {
        findings.push({
          severity: "error",
          code: "missing_database_field",
          message: `Production database ${field} must use a placeholder or explicit value`,
          field: `database.${field}`,
        });
      }
    }
  }

  const summary = {
    errors: findings.filter((finding) => finding.severity === "error").length,
    warnings: findings.filter((finding) => finding.severity === "warning").length,
    info: findings.filter((finding) => finding.severity === "info").length,
  };

  return EnvironmentValidationReportSchema.parse({
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    workspaceName,
    profileId: profile.id,
    profileKind: profile.kind,
    passed: summary.errors === 0,
    summary,
    findings,
  });
}

export async function saveEnvironmentValidationReport(
  workspaceRoot: string,
  report: EnvironmentValidationReport,
): Promise<string> {
  const reportPath = path.join(workspaceRoot, FDT_ENVIRONMENT_VALIDATION_REPORT);
  await mkdir(path.dirname(reportPath), { recursive: true });
  await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");
  return reportPath;
}

function diffStringMaps(
  fromMap: Map<string, string>,
  toMap: Map<string, string>,
  prefix: string,
): EnvironmentDiffReport["convars"] {
  const entries: EnvironmentDiffReport["convars"] = [];
  const keys = new Set([...fromMap.keys(), ...toMap.keys()]);

  for (const key of [...keys].sort((a, b) => a.localeCompare(b))) {
    const from = fromMap.get(key);
    const to = toMap.get(key);

    if (from === undefined && to !== undefined) {
      entries.push({ field: `${prefix}.${key}`, from: undefined, to, changeType: "added" });
    } else if (from !== undefined && to === undefined) {
      entries.push({ field: `${prefix}.${key}`, from, to: undefined, changeType: "removed" });
    } else if (from !== to) {
      entries.push({ field: `${prefix}.${key}`, from, to, changeType: "changed" });
    }
  }

  return entries;
}

export function compareEnvironmentProfiles(input: {
  workspaceName: string;
  from: EnvironmentProfile;
  to: EnvironmentProfile;
  fromEnsureOrder: string[];
  toEnsureOrder: string[];
}): EnvironmentDiffReport {
  const { workspaceName, from, to, fromEnsureOrder, toEnsureOrder } = input;

  const fromConvars = new Map(from.convars.map((convar) => [convar.key, convar.value]));
  const toConvars = new Map(to.convars.map((convar) => [convar.key, convar.value]));
  const fromSecrets = new Map(from.secrets.map((secret) => [secret.key, secret.placeholder]));
  const toSecrets = new Map(to.secrets.map((secret) => [secret.key, secret.placeholder]));

  const convars = diffStringMaps(fromConvars, toConvars, "convar");
  const secrets = diffStringMaps(fromSecrets, toSecrets, "secret");

  const settings: EnvironmentDiffReport["settings"] = [];
  const settingFields: Array<[string, string | number, string | number]> = [
    ["serverName", from.serverName, to.serverName],
    ["maxClients", from.maxClients, to.maxClients],
    ["onesync", from.onesync, to.onesync],
    ["endpoint", from.endpoint, to.endpoint],
  ];

  for (const [field, fromValue, toValue] of settingFields) {
    if (fromValue !== toValue) {
      settings.push({
        field,
        from: String(fromValue),
        to: String(toValue),
        changeType: "changed",
      });
    }
  }

  const added = toEnsureOrder.filter((resource) => !fromEnsureOrder.includes(resource));
  const removed = fromEnsureOrder.filter((resource) => !toEnsureOrder.includes(resource));
  const reordered =
    fromEnsureOrder.length === toEnsureOrder.length &&
    fromEnsureOrder.some((resource, index) => resource !== toEnsureOrder[index]);

  return EnvironmentDiffReportSchema.parse({
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    workspaceName,
    fromProfileId: from.id,
    toProfileId: to.id,
    summary: {
      convarChanges: convars.length,
      secretChanges: secrets.length,
      resourceOrderChanges: added.length + removed.length + (reordered ? 1 : 0),
      settingChanges: settings.length,
    },
    convars,
    secrets,
    settings,
    resourceOrder: {
      added,
      removed,
      reordered,
      from: fromEnsureOrder,
      to: toEnsureOrder,
    },
  });
}

export async function buildEnvironmentDiffReport(
  workspaceRoot: string,
  workspace: Workspace,
  fromRef: string,
  toRef: string,
): Promise<EnvironmentDiffReport> {
  const registry = await loadEnvironmentRegistry(workspaceRoot);
  const from = resolveEnvironmentProfile(registry, fromRef);
  const to = resolveEnvironmentProfile(registry, toRef);

  if (!from) {
    throw new Error(`Environment profile not found: ${fromRef}`);
  }
  if (!to) {
    throw new Error(`Environment profile not found: ${toRef}`);
  }

  const [fromEnsureOrder, toEnsureOrder] = await Promise.all([
    buildResourceEnsureOrder(workspaceRoot, workspace, from),
    buildResourceEnsureOrder(workspaceRoot, workspace, to),
  ]);

  return compareEnvironmentProfiles({
    workspaceName: workspace.name,
    from,
    to,
    fromEnsureOrder,
    toEnsureOrder,
  });
}

export async function saveEnvironmentDiffReport(
  workspaceRoot: string,
  report: EnvironmentDiffReport,
): Promise<string> {
  const reportPath = path.join(workspaceRoot, FDT_ENVIRONMENT_DIFF_REPORT);
  await mkdir(path.dirname(reportPath), { recursive: true });
  await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");
  return reportPath;
}

export function renderEnvironmentDiffMarkdown(report: EnvironmentDiffReport): string {
  const lines = [
    `# Environment Diff: ${report.fromProfileId} → ${report.toProfileId}`,
    "",
    `Generated: ${report.generatedAt}`,
    "",
    "## Summary",
    "",
    `- Convar changes: ${report.summary.convarChanges}`,
    `- Secret changes: ${report.summary.secretChanges}`,
    `- Setting changes: ${report.summary.settingChanges}`,
    `- Resource order changes: ${report.summary.resourceOrderChanges}`,
    "",
  ];

  if (report.settings.length > 0) {
    lines.push("## Settings", "");
    for (const entry of report.settings) {
      lines.push(`- **${entry.field}**: ${entry.from} → ${entry.to}`);
    }
    lines.push("");
  }

  if (report.convars.length > 0) {
    lines.push("## Convars", "");
    for (const entry of report.convars) {
      lines.push(`- **${entry.field}** (${entry.changeType}): ${entry.from ?? "—"} → ${entry.to ?? "—"}`);
    }
    lines.push("");
  }

  if (report.secrets.length > 0) {
    lines.push("## Secrets", "");
    for (const entry of report.secrets) {
      lines.push(`- **${entry.field}** (${entry.changeType}): ${entry.from ?? "—"} → ${entry.to ?? "—"}`);
    }
    lines.push("");
  }

  lines.push("## Resource ensure order", "");
  if (report.resourceOrder.reordered) {
    lines.push("- Order changed between environments");
  }
  if (report.resourceOrder.added.length > 0) {
    lines.push(`- Added: ${report.resourceOrder.added.join(", ")}`);
  }
  if (report.resourceOrder.removed.length > 0) {
    lines.push(`- Removed: ${report.resourceOrder.removed.join(", ")}`);
  }

  return `${lines.join("\n")}\n`;
}

export async function resolveProfileForGeneration(
  workspaceRoot: string,
  ref?: string,
): Promise<EnvironmentProfile> {
  const registry = await loadEnvironmentRegistry(workspaceRoot);
  const resolvedRef = ref ?? registry.defaultProfileId;
  const profile = resolveEnvironmentProfile(registry, resolvedRef);

  if (!profile) {
    throw new Error(`Environment profile not found: ${resolvedRef}`);
  }

  return profile;
}
