import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import {
  EnvironmentProfileSchema,
  EnvironmentRegistrySchema,
  type EnvironmentKind,
  type EnvironmentProfile,
  type EnvironmentRegistry,
  type Workspace,
} from "@fdt/schemas";
import { FDT_ENVIRONMENT_PROFILES_FILE } from "./workspace.js";

const CORE_ENSURE_PREFIX = [
  "sessionmanager",
  "mapmanager",
  "chat",
  "spawnmanager",
  "basic-gamemode",
  "hardcap",
];

function emptyRegistry(): EnvironmentRegistry {
  return {
    schemaVersion: 1,
    updatedAt: new Date().toISOString(),
    defaultProfileId: "local",
    profiles: [],
  };
}

export function resolveEnvironmentProfilesPath(workspaceRoot: string): string {
  return path.join(workspaceRoot, FDT_ENVIRONMENT_PROFILES_FILE);
}

export async function loadEnvironmentRegistry(workspaceRoot: string): Promise<EnvironmentRegistry> {
  const profilesPath = resolveEnvironmentProfilesPath(workspaceRoot);
  if (!existsSync(profilesPath)) {
    return emptyRegistry();
  }

  const raw = await readFile(profilesPath, "utf8");
  return EnvironmentRegistrySchema.parse(JSON.parse(raw));
}

export async function saveEnvironmentRegistry(
  workspaceRoot: string,
  registry: EnvironmentRegistry,
): Promise<string> {
  const profilesPath = resolveEnvironmentProfilesPath(workspaceRoot);
  await mkdir(path.dirname(profilesPath), { recursive: true });

  const payload: EnvironmentRegistry = {
    ...registry,
    updatedAt: new Date().toISOString(),
  };

  await writeFile(profilesPath, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
  return profilesPath;
}

export async function listEnvironmentProfiles(workspaceRoot: string): Promise<EnvironmentProfile[]> {
  const registry = await loadEnvironmentRegistry(workspaceRoot);
  return [...registry.profiles].sort((a, b) => a.kind.localeCompare(b.kind));
}

export function resolveEnvironmentProfile(
  registry: EnvironmentRegistry,
  ref: string,
): EnvironmentProfile | null {
  return (
    registry.profiles.find((profile) => profile.id === ref) ??
    registry.profiles.find((profile) => profile.kind === ref) ??
    registry.profiles.find((profile) => profile.label.toLowerCase() === ref.toLowerCase()) ??
    null
  );
}

export async function getEnvironmentProfile(
  workspaceRoot: string,
  ref: string,
): Promise<EnvironmentProfile | null> {
  const registry = await loadEnvironmentRegistry(workspaceRoot);
  return resolveEnvironmentProfile(registry, ref);
}

export async function upsertEnvironmentProfile(
  workspaceRoot: string,
  profile: EnvironmentProfile,
): Promise<EnvironmentProfile> {
  const parsed = EnvironmentProfileSchema.parse(profile);
  const registry = await loadEnvironmentRegistry(workspaceRoot);
  const index = registry.profiles.findIndex((existing) => existing.id === parsed.id);

  if (index >= 0) {
    registry.profiles[index] = parsed;
  } else {
    registry.profiles.push(parsed);
  }

  registry.profiles.sort((a, b) => a.kind.localeCompare(b.kind));
  await saveEnvironmentRegistry(workspaceRoot, registry);
  return parsed;
}

function defaultProfile(kind: EnvironmentKind, workspace: Workspace): EnvironmentProfile {
  const baseSecrets = [
    {
      key: "svLicense",
      placeholder: "{{svLicense}}",
      description: "FiveM server license key",
      requiredInProduction: true,
    },
    {
      key: "steam_webApiKey",
      placeholder: "{{steam_webApiKey}}",
      description: "Steam Web API key",
      requiredInProduction: kind === "production",
    },
  ];

  const baseConvars = [
    { key: "sv_hostname", value: kind === "production" ? "{{serverName}}" : workspace.name },
    { key: "sv_projectName", value: workspace.name },
    { key: "sv_projectDesc", value: `Generated by FiveM DevOps Toolkit (${kind})` },
  ];

  if (kind === "local" || kind === "dev") {
    baseConvars.push({ key: "sv_enforceGameBuild", value: "3095" });
  }

  const database =
    workspace.database && (kind === "staging" || kind === "production")
      ? {
          type: workspace.database.type === "postgres" ? ("postgres" as const) : ("mysql" as const),
          host: "{{dbHost}}",
          port: workspace.database.type === "postgres" ? 5432 : 3306,
          username: "{{dbUsername}}",
          password: "{{dbPassword}}",
          database: "{{dbName}}",
          connectionString: "{{dbConnectionString}}",
        }
      : kind === "dev"
        ? {
            type: "mysql" as const,
            host: "localhost",
            port: 3306,
            username: "root",
            password: "",
            database: workspace.database?.connectionName ?? "fivem_dev",
          }
        : undefined;

  return EnvironmentProfileSchema.parse({
    id: kind,
    kind,
    label: kind.charAt(0).toUpperCase() + kind.slice(1),
    serverName: kind === "production" ? "{{serverName}}" : `${workspace.name} (${kind})`,
    maxClients: kind === "production" ? 128 : kind === "staging" ? 64 : 32,
    onesync: kind === "local" ? "legacy" : "on",
    endpoint: kind === "production" ? "0.0.0.0:30120" : "127.0.0.1:30120",
    convars: baseConvars,
    secrets: baseSecrets,
    extraServerCfgLines: [],
    database,
    recipeMeta: {
      name: `${workspace.name}-${kind}`,
      version: "1.0.0",
      author: "FiveM DevOps Toolkit",
      description: `${workspace.name} ${kind} environment scaffold`,
    },
  });
}

export async function initEnvironmentProfiles(
  workspaceRoot: string,
  workspace: Workspace,
): Promise<EnvironmentRegistry> {
  const kinds: EnvironmentKind[] = ["local", "dev", "staging", "production"];
  const profiles = kinds.map((kind) => defaultProfile(kind, workspace));

  const registry: EnvironmentRegistry = {
    schemaVersion: 1,
    updatedAt: new Date().toISOString(),
    defaultProfileId: "dev",
    profiles,
  };

  await saveEnvironmentRegistry(workspaceRoot, registry);
  return registry;
}

export function prioritizeCoreEnsureOrder(resources: string[]): string[] {
  const unique = [...new Set(resources)];
  const prioritized: string[] = [];

  for (const core of CORE_ENSURE_PREFIX) {
    if (unique.includes(core)) {
      prioritized.push(core);
    }
  }

  for (const resource of unique.sort((a, b) => a.localeCompare(b))) {
    if (!prioritized.includes(resource)) {
      prioritized.push(resource);
    }
  }

  return prioritized;
}
