import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { deriveMapIdFromResourceName } from "./map-store.js";

export interface MapResourceFile {
  relativePath: string;
  content: string;
}

function sanitizeResourceName(name: string): string {
  const cleaned = name.trim().toLowerCase().replace(/[^a-z0-9_]+/g, "_");
  if (!/^[a-z][a-z0-9_]*$/.test(cleaned)) {
    throw new Error("Resource name must start with a letter and use lowercase letters, numbers, or underscores");
  }
  return cleaned;
}

function defaultMapId(resourceName: string): string {
  return deriveMapIdFromResourceName(resourceName);
}

export function generateMapResource(options: {
  resourceName: string;
  label?: string;
  mapId?: string;
}): MapResourceFile[] {
  const resourceName = sanitizeResourceName(options.resourceName);
  const label = options.label ?? resourceName.replace(/_/g, " ");
  const mapId = options.mapId ?? defaultMapId(resourceName);

  return [
    {
      relativePath: "fxmanifest.lua",
      content: [
        "fx_version 'cerulean'",
        "game 'gta5'",
        "",
        `name '${label.replace(/'/g, "\\'")}'`,
        "this_is_a_map 'yes'",
        "",
        "files {",
        "    'data/entrances.json',",
        "    'data/doors.json',",
        "    'data/blips.json',",
        "    'data/test_points.json',",
        "}",
        "",
      ].join("\n"),
    },
    {
      relativePath: "data/entrances.json",
      content: `${JSON.stringify({ schemaVersion: 1, mapId, entrances: [] }, null, 2)}\n`,
    },
    {
      relativePath: "data/doors.json",
      content: `${JSON.stringify({ schemaVersion: 1, mapId, doors: [] }, null, 2)}\n`,
    },
    {
      relativePath: "data/blips.json",
      content: `${JSON.stringify({ schemaVersion: 1, mapId, blips: [] }, null, 2)}\n`,
    },
    {
      relativePath: "data/test_points.json",
      content: `${JSON.stringify({ schemaVersion: 1, mapId, testPoints: [] }, null, 2)}\n`,
    },
    {
      relativePath: "data/notes.md",
      content: [
        `# ${label}`,
        "",
        "Generated by `fdt map new`.",
        "",
        "## Checklist",
        "",
        "- Add `.ymap` / `.ytyp` / `.ybn` assets to `stream/`",
        "- Document entrance coordinates in `data/entrances.json`",
        "- Add QA teleport points in `data/test_points.json`",
        "",
      ].join("\n"),
    },
    {
      relativePath: "stream/.gitkeep",
      content: "",
    },
    {
      relativePath: "screenshots/.gitkeep",
      content: "",
    },
    {
      relativePath: "README.md",
      content: [
        `# ${label}`,
        "",
        "Map/MLO resource scaffold generated by FiveM DevOps Toolkit.",
        "",
        "Run `fdt map audit --resource " + resourceName + "` after adding stream assets.",
        "",
      ].join("\n"),
    },
  ];
}

export interface WriteMapResourceOptions {
  workspaceRoot: string;
  resourcesRoot: string;
  resourceName: string;
  label?: string;
  mapId?: string;
  force?: boolean;
}

export async function writeMapResource(options: WriteMapResourceOptions): Promise<string> {
  const resourceName = sanitizeResourceName(options.resourceName);
  const resourceRoot = path.resolve(options.workspaceRoot, options.resourcesRoot, resourceName);

  if (options.force !== true) {
    const { access } = await import("node:fs/promises");
    try {
      await access(resourceRoot);
      throw new Error(`Resource folder already exists: ${resourceRoot}. Pass --force to overwrite scaffold files.`);
    } catch (error) {
      if (error instanceof Error && error.message.includes("already exists")) {
        throw error;
      }
    }
  }

  const files = generateMapResource(options);
  for (const file of files) {
    const targetPath = path.join(resourceRoot, file.relativePath);
    await mkdir(path.dirname(targetPath), { recursive: true });
    await writeFile(targetPath, file.content, "utf8");
  }

  return resourceRoot;
}
