import { describe, expect, it } from "vitest";
import type { Item, FdtDomainModel } from "@fdt/schemas";
import { customJsonAdapter } from "./custom-json.js";
import { esxAdapter } from "./esx.js";
import { oxInventoryAdapter } from "./ox-inventory.js";
import { qbcoreAdapter } from "./qbcore.js";
import { qboxAdapter } from "./qbox.js";

const FIXTURE_ITEMS: Item[] = [
  {
    id: "sandwich",
    label: "Sandwich",
    description: "A tasty sandwich",
    category: "food",
    icon: "sandwich.png",
    weight: 0.2,
    stackable: true,
    unique: false,
    usable: true,
    metadata: {},
  },
  {
    id: "water_bottle",
    label: "Water Bottle",
    description: "Stay hydrated",
    category: "drink",
    weight: 0.5,
    stackable: true,
    unique: false,
    usable: true,
    metadata: {},
  },
];

const model: FdtDomainModel = {
  items: FIXTURE_ITEMS,
  vehicles: [],
  businesses: [],
  maps: [],
  jobs: [],
  gangs: [],
  clothingPacks: [],
  shops: [],
  craftingRecipes: [],
};
const generatedAt = "2026-06-21T00:00:00.000Z";

describe("custom-json adapter", () => {
  it("exports deterministic JSON", async () => {
    const result = await customJsonAdapter.export(model, { generatedAt });
    expect(result.files).toHaveLength(1);
    expect(result.files[0]?.relativePath).toBe("items.json");
    expect(result.files[0]?.content).toMatchInlineSnapshot(`
      "{
        "schemaVersion": 1,
        "generatedAt": "2026-06-21T00:00:00.000Z",
        "items": [
          {
            "id": "sandwich",
            "label": "Sandwich",
            "description": "A tasty sandwich",
            "category": "food",
            "icon": "sandwich.png",
            "weight": 0.2,
            "stackable": true,
            "unique": false,
            "usable": true,
            "metadata": {}
          },
          {
            "id": "water_bottle",
            "label": "Water Bottle",
            "description": "Stay hydrated",
            "category": "drink",
            "weight": 0.5,
            "stackable": true,
            "unique": false,
            "usable": true,
            "metadata": {}
          }
        ]
      }
      "
    `);
  });

  it("exports vehicles and businesses when present", async () => {
    const result = await customJsonAdapter.export(
      {
        items: [],
        vehicles: [
          {
            spawnName: "meta_cvpi",
            displayName: "Meta CVPI",
            category: "emergency",
            emergency: true,
            restrictedJobs: [],
            metadata: {},
          },
        ],
        businesses: [
          {
            id: "biz_shop",
            label: "Shop",
            type: "shop",
            registerEnabled: true,
            metadata: {},
          },
        ],
        maps: [],
        jobs: [],
        gangs: [],
        clothingPacks: [],
        shops: [],
        craftingRecipes: [],
      },
      { generatedAt },
    );

    expect(result.files.map((file) => file.relativePath)).toEqual([
      "items.json",
      "vehicles.json",
      "vehicle-shop.json",
      "businesses.json",
    ]);
  });

  it("exports jobs and gangs when present", async () => {
    const result = await customJsonAdapter.export(
      {
        items: [],
        vehicles: [],
        businesses: [],
        maps: [],
        jobs: [
          {
            id: "police",
            label: "Police",
            type: "public_safety",
            defaultDuty: true,
            grades: [{ id: "recruit", level: 0, label: "Recruit", payment: 50, permissions: [] }],
            locations: [],
            metadata: {},
          },
        ],
        gangs: [
          {
            id: "ballas",
            label: "Ballas",
            type: "gang",
            zoneIds: ["territory_ballas"],
            territoryIds: ["territory_ballas"],
            grades: [{ id: "member", level: 0, label: "Member", permissions: [] }],
            metadata: {},
          },
        ],
        clothingPacks: [],
        shops: [],
        craftingRecipes: [],
      },
      { generatedAt },
    );

    expect(result.files.map((file) => file.relativePath)).toEqual(["items.json", "jobs.json", "gangs.json"]);
  });
});

describe("qbcore adapter", () => {
  it("exports deterministic Lua", async () => {
    const result = await qbcoreAdapter.export(model, { generatedAt });
    expect(result.files).toHaveLength(1);
    expect(result.files[0]?.relativePath).toBe("shared/items.lua");
    expect(result.files[0]?.content).toBe(
      [
        "-- Generated by FiveM DevOps Toolkit",
        "-- Adapter: qbcore",
        "-- Generated at: 2026-06-21T00:00:00.000Z",
        "QBShared = QBShared or {}",
        "QBShared.Items = QBShared.Items or {}",
        "",
        "    ['sandwich'] = {",
        "        name = 'sandwich',",
        "        label = 'Sandwich',",
        "        weight = 200,",
        "        type = 'item',",
        "        image = 'sandwich.png',",
        "        unique = false,",
        "        useable = true,",
        "        shouldClose = true,",
        "        description = 'A tasty sandwich',",
        "    },",
        "    ['water_bottle'] = {",
        "        name = 'water_bottle',",
        "        label = 'Water Bottle',",
        "        weight = 500,",
        "        type = 'item',",
        "        image = 'water_bottle.png',",
        "        unique = false,",
        "        useable = true,",
        "        shouldClose = true,",
        "        description = 'Stay hydrated',",
        "    },",
        "",
      ].join("\n"),
    );
  });

  it("exports shared/jobs.lua when jobs are present", async () => {
    const result = await qbcoreAdapter.export(
      {
        ...model,
        jobs: [
          {
            id: "police",
            label: "Police",
            type: "public_safety",
            defaultDuty: true,
            grades: [{ id: "recruit", level: 0, label: "Recruit", payment: 50, permissions: [] }],
            locations: [],
            metadata: {},
          },
        ],
      },
      { generatedAt },
    );

    expect(result.files).toHaveLength(2);
    expect(result.files[1]?.relativePath).toBe("shared/jobs.lua");
    expect(result.files[1]?.content).toContain("['police']");
    expect(result.files[1]?.content).toContain("QBShared.Jobs");
  });
});

describe("ox-inventory adapter", () => {
  it("exports merge-friendly ox_inventory lua", async () => {
    const result = await oxInventoryAdapter.export(model, { generatedAt });
    expect(result.files[0]?.relativePath).toBe("data/items.fdt.lua");
    expect(result.files[0]?.content).toContain("return {");
    expect(result.files[0]?.content).toContain("stack = true");
    expect(result.files[0]?.content).toContain("client = {");
  });
});

describe("qbox adapter", () => {
  it("targets ox_inventory merge path for qbox servers", async () => {
    const result = await qboxAdapter.export(model, { generatedAt });
    expect(result.files[0]?.relativePath).toBe("ox_inventory/data/items.fdt.lua");
    expect(result.files[0]?.content).toContain("Qbox uses ox_inventory");
  });

  it("exports qbox clothing and jobs alongside ox_inventory items", async () => {
    const result = await qboxAdapter.export(
      {
        ...model,
        jobs: [
          {
            id: "police",
            label: "Police",
            type: "public_safety",
            defaultDuty: true,
            grades: [{ id: "recruit", level: 0, label: "Recruit", payment: 50, permissions: [] }],
            locations: [],
            metadata: {},
          },
        ],
        clothingPacks: [
          {
            id: "pack_a",
            label: "Pack A",
            resourceName: "meta_clothing_a",
            genderScope: "shared",
            status: "scanned",
            tags: [],
            drawables: [
              {
                id: "drw_jacket",
                label: "Jacket",
                category: "tops",
                componentId: 11,
                drawableId: 3,
                gender: "male",
                fileName: "jacket.ydd",
                relativePath: "stream/jacket.ydd",
                textures: [],
                restrictedJobs: [],
                restrictedGangs: [],
                tags: [],
              },
            ],
            metadata: {},
          },
        ],
      },
      { generatedAt },
    );

    expect(result.files.map((file) => file.relativePath)).toEqual([
      "ox_inventory/data/items.fdt.lua",
      "qbx_core/shared/fdt_jobs.lua",
      "qbx_core/shared/fdt_clothing_catalog.lua",
      "illenium-appearance/shared/fdt_clothing_catalog.lua",
    ]);
    expect(result.files[2]?.content).toContain("Adapter: qbox");
  });
});

describe("esx adapter", () => {
  it("exports SQL rows", async () => {
    const result = await esxAdapter.export(model, { generatedAt });
    expect(result.files[0]?.relativePath).toBe("esx/items.sql");
    expect(result.files[0]?.content).toContain("INSERT INTO `items`");
    expect(result.files[0]?.content).toContain("'sandwich'");
  });

  it("can include ox_inventory merge file for ESX + ox stacks", async () => {
    const result = await esxAdapter.export(model, { generatedAt, includeOxInventory: true });
    expect(result.files).toHaveLength(2);
    expect(result.files[1]?.relativePath).toBe("ox_inventory/data/items.fdt.lua");
  });
});
