import type { CraftingRecipe, FdtDomainModel, Shop, ShopItemEntry } from "@fdt/schemas";
import { luaString } from "./lua-utils.js";

export function sortedShops(model: FdtDomainModel): Shop[] {
  return [...model.shops].sort((a, b) => a.id.localeCompare(b.id));
}

export function sortedCraftingRecipes(model: FdtDomainModel): CraftingRecipe[] {
  return [...model.craftingRecipes].sort((a, b) => a.id.localeCompare(b.id));
}

function renderVector4(coords: { x: number; y: number; z: number; w?: number }): string {
  return `vector4(${coords.x}, ${coords.y}, ${coords.z}, ${coords.w ?? 0})`;
}

function renderVec3(coords: { x: number; y: number; z: number }): string {
  return `vec3(${coords.x}, ${coords.y}, ${coords.z})`;
}

function mapQbCurrency(currency: Shop["currency"]): string {
  switch (currency) {
    case "bank":
      return "bank";
    case "crypto":
      return "crypto";
    case "item":
      return "item";
    case "custom":
      return "custom";
    default:
      return "cash";
  }
}

function renderQbShopProducts(items: ShopItemEntry[]): string {
  const sorted = [...items].sort((a, b) => a.itemId.localeCompare(b.itemId));
  return sorted
    .map((entry) => {
      const parts = [`name = ${luaString(entry.itemId)}`, `price = ${entry.price}`];
      if (entry.stock !== undefined) {
        parts.push(`amount = ${entry.stock}`);
      }
      if (entry.minGrade !== undefined) {
        parts.push(`requiredGrade = ${entry.minGrade}`);
      }
      return `            { ${parts.join(", ")} },`;
    })
    .join("\n");
}

function renderQbShopEntry(shop: Shop): string {
  const lines = [
    `    [${luaString(shop.id)}] = {`,
    `        label = ${luaString(shop.label)},`,
    `        type = ${luaString(shop.type)},`,
    `        currency = ${luaString(mapQbCurrency(shop.currency))},`,
  ];

  if (shop.jobId) {
    lines.push(`        requiredJob = ${luaString(shop.jobId)},`);
  }
  if (shop.gangId) {
    lines.push(`        requiredGang = ${luaString(shop.gangId)},`);
  }
  if (shop.blip?.sprite !== undefined) {
    lines.push(`        blipSprite = ${shop.blip.sprite},`);
  }
  if (shop.blip?.color !== undefined) {
    lines.push(`        blipColor = ${shop.blip.color},`);
  }
  if (shop.blip?.label) {
    lines.push(`        blipLabel = ${luaString(shop.blip.label)},`);
  }

  if (shop.locations.length > 0) {
    lines.push("        locations = {");
    for (const location of shop.locations) {
      lines.push(`            ${renderVector4(location.coords)},`);
    }
    lines.push("        },");
  }

  lines.push("        products = {");
  lines.push(renderQbShopProducts(shop.items));
  lines.push("        },");
  lines.push("    },");

  return lines.join("\n");
}

export function renderQbShopsLua(model: FdtDomainModel, generatedAt: string, adapterId = "qbcore"): string {
  const shops = sortedShops(model);
  const body = shops.map(renderQbShopEntry).join("\n");
  const mergeHint =
    adapterId === "qbox"
      ? "-- Merge into qb-shops, qbx_shops, or a custom commerce resource."
      : "-- Merge into qb-shops/config.lua or load as shared/fdt_shops.lua.";

  return [
    "-- Generated by FiveM DevOps Toolkit",
    `-- Adapter: ${adapterId}`,
    `-- Generated at: ${generatedAt}`,
    mergeHint,
    "FDTShops = FDTShops or {}",
    "FDTShops.Locations = FDTShops.Locations or {}",
    "",
    body,
    "",
  ].join("\n");
}

function renderQbCraftingCosts(recipe: CraftingRecipe): string {
  const sorted = [...recipe.inputs].sort((a, b) => a.itemId.localeCompare(b.itemId));
  if (sorted.length === 0) {
    return "            costs = {},";
  }

  const entries = sorted.map((input) => `[${luaString(input.itemId)}] = ${input.amount}`).join(", ");
  return `            costs = { ${entries} },`;
}

function renderQbCraftingRecipe(recipe: CraftingRecipe): string {
  const primaryOutput = recipe.outputs[0]!;
  const lines = [
    "        {",
    `            id = ${luaString(recipe.id)},`,
    `            label = ${luaString(recipe.label)},`,
    `            item = ${luaString(primaryOutput.itemId)},`,
    `            amount = ${primaryOutput.amount},`,
  ];

  if (recipe.bench) {
    lines.push(`            bench = ${luaString(recipe.bench)},`);
  }
  if (recipe.durationSeconds !== undefined) {
    lines.push(`            duration = ${Math.round(recipe.durationSeconds * 1000)},`);
  }
  if (recipe.jobId) {
    lines.push(`            requiredJob = ${luaString(recipe.jobId)},`);
  }
  if (recipe.gangId) {
    lines.push(`            requiredGang = ${luaString(recipe.gangId)},`);
  }
  if (recipe.minGrade !== undefined) {
    lines.push(`            requiredGrade = ${recipe.minGrade},`);
  }

  lines.push(renderQbCraftingCosts(recipe));

  if (recipe.outputs.length > 1) {
    lines.push("            extraOutputs = {");
    for (const output of recipe.outputs.slice(1)) {
      lines.push(
        `                { item = ${luaString(output.itemId)}, amount = ${output.amount} },`,
      );
    }
    lines.push("            },");
  }

  lines.push("        },");
  return lines.join("\n");
}

export function renderQbCraftingLua(
  model: FdtDomainModel,
  generatedAt: string,
  adapterId = "qbcore",
): string {
  const recipes = sortedCraftingRecipes(model);
  const body = recipes.map(renderQbCraftingRecipe).join("\n");
  const mergeHint =
    adapterId === "qbox"
      ? "-- Merge into qb-crafting, qbx_crafting, or a custom bench resource."
      : "-- Merge into qb-crafting/config.lua or load as shared/fdt_crafting.lua.";

  return [
    "-- Generated by FiveM DevOps Toolkit",
    `-- Adapter: ${adapterId}`,
    `-- Generated at: ${generatedAt}`,
    mergeHint,
    "FDTCrafting = FDTCrafting or {}",
    "FDTCrafting.Recipes = FDTCrafting.Recipes or {}",
    "FDTCrafting.Recipes = {",
    body,
    "}",
    "",
  ].join("\n");
}

export function renderEsxShopsJson(model: FdtDomainModel, generatedAt: string): string {
  const shops = sortedShops(model).map((shop) => ({
    id: shop.id,
    label: shop.label,
    type: shop.type,
    currency: shop.currency,
    job: shop.jobId,
    gang: shop.gangId,
    blip: shop.blip,
    locations: shop.locations,
    items: [...shop.items]
      .sort((a, b) => a.itemId.localeCompare(b.itemId))
      .map((entry) => ({
        name: entry.itemId,
        price: entry.price,
        stock: entry.stock,
        minGrade: entry.minGrade,
      })),
    metadata: shop.metadata,
  }));

  return `${JSON.stringify(
    {
      schemaVersion: 1,
      generatedAt,
      adapter: "esx",
      shops,
    },
    null,
    2,
  )}\n`;
}

export function renderEsxCraftingJson(model: FdtDomainModel, generatedAt: string): string {
  const recipes = sortedCraftingRecipes(model).map((recipe) => ({
    id: recipe.id,
    label: recipe.label,
    bench: recipe.bench,
    durationSeconds: recipe.durationSeconds,
    job: recipe.jobId,
    gang: recipe.gangId,
    minGrade: recipe.minGrade,
    inputs: [...recipe.inputs].sort((a, b) => a.itemId.localeCompare(b.itemId)),
    outputs: [...recipe.outputs].sort((a, b) => a.itemId.localeCompare(b.itemId)),
    metadata: recipe.metadata,
  }));

  return `${JSON.stringify(
    {
      schemaVersion: 1,
      generatedAt,
      adapter: "esx",
      recipes,
    },
    null,
    2,
  )}\n`;
}

function renderOxShopEntry(shop: Shop): string {
  const lines = [
    `    [${luaString(shop.id)}] = {`,
    `        name = ${luaString(shop.label)},`,
  ];

  if (shop.jobId) {
    const minGrade = shop.items.reduce((max, entry) => Math.max(max, entry.minGrade ?? 0), 0);
    lines.push(`        groups = { ${luaString(shop.jobId)} = ${minGrade} },`);
  } else if (shop.gangId) {
    lines.push(`        groups = { ${luaString(shop.gangId)} = 0 },`);
  }

  lines.push("        inventory = {");
  for (const entry of [...shop.items].sort((a, b) => a.itemId.localeCompare(b.itemId))) {
    const parts = [`name = ${luaString(entry.itemId)}`, `price = ${entry.price}`];
    if (entry.stock !== undefined) {
      parts.push(`count = ${entry.stock}`);
    }
    lines.push(`            { ${parts.join(", ")} },`);
  }
  lines.push("        },");

  if (shop.locations.length > 0) {
    lines.push("        locations = {");
    for (const location of shop.locations) {
      lines.push(`            ${renderVec3(location.coords)},`);
    }
    lines.push("        },");
  }

  if (shop.currency !== "cash") {
    lines.push(`        currency = ${luaString(shop.currency)},`);
  }

  lines.push("    },");
  return lines.join("\n");
}

export function renderOxInventoryShopsLua(model: FdtDomainModel, generatedAt: string): string {
  const shops = sortedShops(model);
  const body = shops.map(renderOxShopEntry).join("\n");

  return [
    "-- Generated by FiveM DevOps Toolkit",
    "-- Adapter: ox-inventory",
    `-- Generated at: ${generatedAt}`,
    "-- Merge entries into ox_inventory/data/shops.lua (do not overwrite the whole file).",
    "return {",
    body,
    "}",
    "",
  ].join("\n");
}

function groupRecipesByBench(recipes: CraftingRecipe[]): Map<string, CraftingRecipe[]> {
  const groups = new Map<string, CraftingRecipe[]>();
  for (const recipe of recipes) {
    const bench = recipe.bench ?? "default";
    const existing = groups.get(bench) ?? [];
    existing.push(recipe);
    groups.set(bench, existing);
  }
  return groups;
}

export function renderOxInventoryCraftingLua(model: FdtDomainModel, generatedAt: string): string {
  const recipes = sortedCraftingRecipes(model);
  const groups = groupRecipesByBench(recipes);
  const benches = [...groups.keys()].sort((a, b) => a.localeCompare(b));

  const benchBlocks = benches.map((benchName) => {
    const benchRecipes = groups.get(benchName) ?? [];
    const lines = ["    {", `        name = ${luaString(benchName)},`, "        items = {"];

    for (const recipe of benchRecipes) {
      const primaryOutput = recipe.outputs[0]!;
      lines.push("            {");
      lines.push(`                name = ${luaString(primaryOutput.itemId)},`);
      lines.push(`                count = ${primaryOutput.amount},`);

      if (recipe.durationSeconds !== undefined) {
        lines.push(`                duration = ${Math.round(recipe.durationSeconds * 1000)},`);
      }

      const ingredients = [...recipe.inputs].sort((a, b) => a.itemId.localeCompare(b.itemId));
      if (ingredients.length > 0) {
        lines.push("                ingredients = {");
        for (const input of ingredients) {
          lines.push(`                    ${luaString(input.itemId)} = ${input.amount},`);
        }
        lines.push("                },");
      }

      if (recipe.jobId) {
        lines.push(`                groups = { ${luaString(recipe.jobId)} = ${recipe.minGrade ?? 0} },`);
      }

      lines.push("            },");
    }

    lines.push("        },", "    },");
    return lines.join("\n");
  });

  return [
    "-- Generated by FiveM DevOps Toolkit",
    "-- Adapter: ox-inventory",
    `-- Generated at: ${generatedAt}`,
    "-- Merge entries into ox_inventory/data/crafting.lua (do not overwrite the whole file).",
    "return {",
    benchBlocks.join("\n"),
    "}",
    "",
  ].join("\n");
}
