import type { Item } from "@fdt/schemas";
import type { AdapterExportOptions, FdtAdapter } from "./types.js";
import { renderEsxClothingCatalogJson } from "./clothing-render.js";
import {
  renderEsxCraftingJson,
  renderEsxShopsJson,
} from "./commerce-render.js";
import { buildOxInventoryExport } from "./ox-inventory-render.js";
import { sortedItems } from "./ox-inventory-render.js";
import { sqlString } from "./lua-utils.js";

function renderEsxSqlRows(items: Item[]): string {
  return items
    .map((item) => {
      const weight = Math.max(1, Math.round(item.weight * 1000));
      const rare = item.economy?.rarity === "rare" || item.economy?.rarity === "epic" ? 1 : 0;
      const canRemove = item.unique ? 0 : 1;
      return `(${sqlString(item.id)}, ${sqlString(item.label)}, ${weight}, ${rare}, ${canRemove})`;
    })
    .join(",\n");
}

export const esxAdapter: FdtAdapter = {
  id: "esx",
  label: "ESX Legacy Items",
  version: "1.0.0",
  capabilities: ["items", "clothing", "shops", "crafting"],

  async export(model, options: AdapterExportOptions = {}) {
    const generatedAt = options.generatedAt ?? new Date().toISOString();
    const items = sortedItems(model);
    const rows = renderEsxSqlRows(items);

    const sql = [
      "-- Generated by FiveM DevOps Toolkit",
      "-- Adapter: esx",
      `-- Generated at: ${generatedAt}`,
      "-- Import into your ESX database `items` table.",
      "-- If you use ox_inventory with ESX, prefer the ox-inventory adapter for in-game items.",
      "",
      "INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES",
      rows,
      "ON DUPLICATE KEY UPDATE",
      "  `label` = VALUES(`label`),",
      "  `weight` = VALUES(`weight`),",
      "  `rare` = VALUES(`rare`),",
      "  `can_remove` = VALUES(`can_remove`);",
      "",
    ].join("\n");

    const files = [
      {
        relativePath: "esx/items.sql",
        content: sql,
      },
    ];

    if (options.includeOxInventory) {
      files.push({
        relativePath: "ox_inventory/data/items.fdt.lua",
        content: buildOxInventoryExport(model, {
          generatedAt,
          adapterId: "esx",
          adapterLabel: "ESX + ox_inventory",
          relativePath: "ox_inventory/data/items.fdt.lua",
          headerLines: ["-- ESX servers using ox_inventory should merge this file instead of SQL."],
        }),
      });
    }

    if (model.clothingPacks.length > 0) {
      files.push({
        relativePath: "esx/clothing_catalog.json",
        content: renderEsxClothingCatalogJson(model, generatedAt),
      });
    }

    if (model.shops.length > 0) {
      files.push({
        relativePath: "esx/shops.json",
        content: renderEsxShopsJson(model, generatedAt),
      });
    }

    if (model.craftingRecipes.length > 0) {
      files.push({
        relativePath: "esx/crafting_recipes.json",
        content: renderEsxCraftingJson(model, generatedAt),
      });
    }

    return {
      adapterId: "esx",
      dryRun: options.dryRun ?? false,
      files,
    };
  },
};
