import type { Item, FdtDomainModel } from "@fdt/schemas";
import { luaBool, luaString } from "./lua-utils.js";

export function sortedItems(model: FdtDomainModel): Item[] {
  return [...model.items].sort((a, b) => a.id.localeCompare(b.id));
}

export function renderOxInventoryItem(item: Item): string {
  const lines = [
    `    [${luaString(item.id)}] = {`,
    `        label = ${luaString(item.label)},`,
    `        weight = ${Math.round(item.weight * 1000)},`,
    `        stack = ${luaBool(item.stackable && !item.unique)},`,
    `        close = ${luaBool(item.usable)},`,
  ];

  if (item.description) {
    lines.push(`        description = ${luaString(item.description)},`);
  }

  const icon = item.icon ?? `${item.id}.png`;
  lines.push("        client = {");
  lines.push(`            image = ${luaString(icon)},`);
  lines.push("        },");

  lines.push("    },");
  return lines.join("\n");
}

export interface OxInventoryExportOptions {
  generatedAt: string;
  adapterLabel: string;
  adapterId: string;
  relativePath: string;
  headerLines?: string[];
}

export function buildOxInventoryExport(
  model: FdtDomainModel,
  options: OxInventoryExportOptions,
): string {
  const items = sortedItems(model);
  const body = items.map(renderOxInventoryItem).join("\n");

  const header = [
    "-- Generated by FiveM DevOps Toolkit",
    `-- Adapter: ${options.adapterId}`,
    `-- Target: ${options.adapterLabel}`,
    `-- Generated at: ${options.generatedAt}`,
    "-- Merge entries into ox_inventory/data/items.lua (do not overwrite the whole file).",
    ...(options.headerLines ?? []),
    "return {",
    body,
    "}",
    "",
  ];

  return header.join("\n");
}
