import type { Item } from "@fdt/schemas";
import type { AdapterExportOptions, FdtAdapter } from "./types.js";
import { luaBool, luaString } from "./lua-utils.js";
import { renderQbClothingCatalogLua } from "./clothing-render.js";
import {
  renderQbCraftingLua,
  renderQbShopsLua,
} from "./commerce-render.js";
import { renderQbVehicleShopLua } from "./vehicle-render.js";
import { renderQbJob, sortedJobs } from "./qbcore-jobs-render.js";
import { sortedItems } from "./ox-inventory-render.js";

function renderQbItem(item: Item): string {
  const lines = [
    `    [${luaString(item.id)}] = {`,
    `        name = ${luaString(item.id)},`,
    `        label = ${luaString(item.label)},`,
    `        weight = ${Math.round(item.weight * 1000)},`,
    `        type = 'item',`,
    `        image = ${luaString(item.icon ?? `${item.id}.png`)},`,
    `        unique = ${luaBool(item.unique)},`,
    `        useable = ${luaBool(item.usable)},`,
    `        shouldClose = ${luaBool(item.usable)},`,
  ];

  if (item.description) {
    lines.push(`        description = ${luaString(item.description)},`);
  }

  lines.push("    },");
  return lines.join("\n");
}

export const qbcoreAdapter: FdtAdapter = {
  id: "qbcore",
  label: "QBCore Items",
  version: "1.0.0",
  capabilities: ["items", "jobs", "clothing", "vehicles", "shops", "crafting"],

  async export(model, options: AdapterExportOptions = {}) {
    const generatedAt = options.generatedAt ?? new Date().toISOString();
    const items = sortedItems(model);
    const body = items.map(renderQbItem).join("\n");

    const files = [
      {
        relativePath: "shared/items.lua",
        content: [
          "-- Generated by FiveM DevOps Toolkit",
          `-- Adapter: qbcore`,
          `-- Generated at: ${generatedAt}`,
          "QBShared = QBShared or {}",
          "QBShared.Items = QBShared.Items or {}",
          "",
          body,
          "",
        ].join("\n"),
      },
    ];

    if (model.jobs.length > 0) {
      const jobs = sortedJobs(model);
      files.push({
        relativePath: "shared/jobs.lua",
        content: [
          "-- Generated by FiveM DevOps Toolkit",
          `-- Adapter: qbcore`,
          `-- Generated at: ${generatedAt}`,
          "QBShared = QBShared or {}",
          "QBShared.Jobs = QBShared.Jobs or {}",
          "",
          jobs.map(renderQbJob).join("\n"),
          "",
        ].join("\n"),
      });
    }

    if (model.clothingPacks.length > 0) {
      files.push({
        relativePath: "shared/clothing_catalog.lua",
        content: renderQbClothingCatalogLua(model, generatedAt),
      });
    }

    if (model.vehicles.length > 0) {
      files.push({
        relativePath: "shared/vehicle_shop.lua",
        content: renderQbVehicleShopLua(model, generatedAt),
      });
    }

    if (model.shops.length > 0) {
      files.push({
        relativePath: "shared/fdt_shops.lua",
        content: renderQbShopsLua(model, generatedAt, "qbcore"),
      });
    }

    if (model.craftingRecipes.length > 0) {
      files.push({
        relativePath: "shared/fdt_crafting.lua",
        content: renderQbCraftingLua(model, generatedAt, "qbcore"),
      });
    }

    return {
      adapterId: "qbcore",
      dryRun: options.dryRun ?? false,
      files,
    };
  },
};
