import type { FdtDomainModel } from "@fdt/schemas";
import type { AdapterExportOptions, FdtAdapter } from "./types.js";
import { buildOxInventoryExport } from "./ox-inventory-render.js";
import { renderQboxClothingCatalogLua } from "./clothing-render.js";
import {
  renderQbCraftingLua,
  renderQbShopsLua,
} from "./commerce-render.js";
import { renderQboxVehicleShopLua } from "./vehicle-render.js";
import { renderQbJob, sortedJobs } from "./qbcore-jobs-render.js";

export const qboxAdapter: FdtAdapter = {
  id: "qbox",
  label: "Qbox (ox_inventory + appearance)",
  version: "1.0.0",
  capabilities: ["items", "jobs", "clothing", "vehicles", "shops", "crafting"],

  async export(model, options: AdapterExportOptions = {}) {
    const generatedAt = options.generatedAt ?? new Date().toISOString();
    const files = [
      {
        relativePath: "ox_inventory/data/items.fdt.lua",
        content: buildOxInventoryExport(model, {
          generatedAt,
          adapterId: "qbox",
          adapterLabel: "Qbox + ox_inventory",
          relativePath: "ox_inventory/data/items.fdt.lua",
          headerLines: [
            "-- Qbox uses ox_inventory as the source of truth for items.",
            "-- qbx_core bridge auto-converts these entries for legacy QBCore scripts.",
            "-- Add client/server exports manually in ox_inventory/data/items.lua when needed.",
          ],
        }),
      },
    ];

    if (model.jobs.length > 0) {
      const jobs = sortedJobs(model);
      files.push({
        relativePath: "qbx_core/shared/fdt_jobs.lua",
        content: [
          "-- Generated by FiveM DevOps Toolkit",
          "-- Adapter: qbox",
          `-- Generated at: ${generatedAt}`,
          "-- Merge into qbx_core or load as a shared script.",
          "QBShared = QBShared or {}",
          "QBShared.Jobs = QBShared.Jobs or {}",
          "",
          jobs.map(renderQbJob).join("\n"),
          "",
        ].join("\n"),
      });
    }

    if (model.clothingPacks.length > 0) {
      files.push({
        relativePath: "qbx_core/shared/fdt_clothing_catalog.lua",
        content: renderQboxClothingCatalogLua(model, generatedAt),
      });
      files.push({
        relativePath: "illenium-appearance/shared/fdt_clothing_catalog.lua",
        content: renderQboxClothingCatalogLua(model, generatedAt),
      });
    }

    if (model.vehicles.length > 0) {
      files.push({
        relativePath: "qbx_core/shared/fdt_vehicle_shop.lua",
        content: renderQboxVehicleShopLua(model, generatedAt),
      });
      files.push({
        relativePath: "qbx_vehicleshop/shared/fdt_vehicle_shop.lua",
        content: renderQboxVehicleShopLua(model, generatedAt),
      });
    }

    if (model.shops.length > 0) {
      files.push({
        relativePath: "qbx_shops/shared/fdt_shops.lua",
        content: renderQbShopsLua(model, generatedAt, "qbox"),
      });
    }

    if (model.craftingRecipes.length > 0) {
      files.push({
        relativePath: "qbx_crafting/shared/fdt_crafting.lua",
        content: renderQbCraftingLua(model, generatedAt, "qbox"),
      });
    }

    return {
      adapterId: "qbox",
      dryRun: options.dryRun ?? false,
      files,
    };
  },
};
