import type { FdtDomainModel, Vehicle } from "@fdt/schemas";
import { luaString } from "./lua-utils.js";

export interface VehicleShopEntry {
  spawnName: string;
  label: string;
  category: string;
  price?: number;
  shop?: string;
  emergency: boolean;
  restrictedJobs: string[];
  resourceName?: string;
}

function sortedVehicles(model: FdtDomainModel): Vehicle[] {
  return [...model.vehicles].sort((a, b) => a.spawnName.localeCompare(b.spawnName));
}

export function buildVehicleShopEntries(model: FdtDomainModel): VehicleShopEntry[] {
  return sortedVehicles(model).map((vehicle) => ({
    spawnName: vehicle.spawnName,
    label: vehicle.displayName,
    category: vehicle.category,
    price: vehicle.price,
    shop: vehicle.shop,
    emergency: vehicle.emergency,
    restrictedJobs: [...vehicle.restrictedJobs].sort(),
    resourceName:
      typeof vehicle.metadata.resourceName === "string" ? vehicle.metadata.resourceName : undefined,
  }));
}

export function renderVehicleShopJson(model: FdtDomainModel, generatedAt: string): string {
  return `${JSON.stringify(
    {
      schemaVersion: 1,
      generatedAt,
      entries: buildVehicleShopEntries(model),
    },
    null,
    2,
  )}\n`;
}

function renderLuaStringArray(values: string[]): string {
  if (values.length === 0) {
    return "{}";
  }
  return `{ ${values.map((value) => luaString(value)).join(", ")} }`;
}

export function renderQboxVehicleShopLua(model: FdtDomainModel, generatedAt: string): string {
  const body = buildVehicleShopEntries(model)
    .map((entry) => {
      const lines = [
        `    [${luaString(entry.spawnName)}] = {`,
        `        label = ${luaString(entry.label)},`,
        `        category = ${luaString(entry.category)},`,
        `        emergency = ${entry.emergency ? "true" : "false"},`,
      ];

      if (entry.price !== undefined) {
        lines.push(`        price = ${entry.price},`);
      }
      if (entry.shop) {
        lines.push(`        shop = ${luaString(entry.shop)},`);
      }
      if (entry.resourceName) {
        lines.push(`        resource = ${luaString(entry.resourceName)},`);
      }
      if (entry.restrictedJobs.length > 0) {
        lines.push(`        restrictedJobs = ${renderLuaStringArray(entry.restrictedJobs)},`);
      }

      lines.push("    },");
      return lines.join("\n");
    })
    .join("\n");

  return [
    "-- Generated by FiveM DevOps Toolkit",
    "-- Adapter: qbox",
    `-- Generated at: ${generatedAt}`,
    "-- Merge into qbx_vehicleshop, qbx_core, or a custom fleet resource.",
    "FDTVehicleShop = FDTVehicleShop or {}",
    "FDTVehicleShop.Entries = FDTVehicleShop.Entries or {}",
    "",
    body,
    "",
  ].join("\n");
}

export function renderQbVehicleShopLua(model: FdtDomainModel, generatedAt: string): string {
  return renderQboxVehicleShopLua(model, generatedAt)
    .replace("-- Adapter: qbox", "-- Adapter: qbcore")
    .replace(
      "-- Merge into qbx_vehicleshop, qbx_core, or a custom fleet resource.",
      "-- Merge into qb-vehicleshop or a custom fleet resource.",
    )
    .replace("FDTVehicleShop", "FDTVehicleShop");
}
